/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class interfacetocpp */

#ifndef _Included_interfacetocpp
#define _Included_interfacetocpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     interfacetocpp
 * Method:    connais
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_interfacetocpp_connais
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
